#!/bin/bash
    
    cd /home/kostafun/Projects/LatentSync
    source venv/bin/activate
    python -m scripts.inference --unet_config_path configs/unet/second_stage.yaml --inference_ckpt_path checkpoints/latentsync_unet.pt --guidance_scale 1 --video_path /home/kostafun/Projects/vidcreate/data/videos/angel2_faceswap.mp4 --audio_path /home/kostafun/Projects/vidcreate/data/voices/voice_1739684265849.mp3 --video_out_path /home/kostafun/Projects/vidcreate/data/results/result_1739684372826.mp4 --start_frame 0
python -m scripts.inference --unet_config_path configs/unet/second_stage.yaml --inference_ckpt_path checkpoints/latentsync_unet.pt --guidance_scale 1 --video_path /home/kostafun/Projects/vidcreate/data/videos/angel2_faceswap.mp4 --audio_path /home/kostafun/Projects/vidcreate/data/voices/voice_1739684530195.mp3 --video_out_path /home/kostafun/Projects/vidcreate/data/results/result_1739684594380.mp4 --start_frame 0
python -m scripts.inference --unet_config_path configs/unet/second_stage.yaml --inference_ckpt_path checkpoints/latentsync_unet.pt --guidance_scale 1 --video_path /home/kostafun/Projects/vidcreate/data/videos/angel2_faceswap.mp4 --audio_path /home/kostafun/Projects/vidcreate/data/voices/voice_1739684699440.mp3 --video_out_path /home/kostafun/Projects/vidcreate/data/results/result_1739684822401.mp4 --start_frame 0
python -m scripts.inference --unet_config_path configs/unet/second_stage.yaml --inference_ckpt_path checkpoints/latentsync_unet.pt --guidance_scale 1 --video_path /home/kostafun/Projects/vidcreate/data/videos/nakortah_00001.mp4 --audio_path /home/kostafun/Projects/vidcreate/data/voices/voice_1739684961532.mp3 --video_out_path /home/kostafun/Projects/vidcreate/data/results/result_1739684988783.mp4 --start_frame 0
python -m scripts.inference --unet_config_path configs/unet/second_stage.yaml --inference_ckpt_path checkpoints/latentsync_unet.pt --guidance_scale 1 --video_path /home/kostafun/Projects/vidcreate/data/videos/nakortah_00001.mp4 --audio_path /home/kostafun/Projects/vidcreate/data/voices/voice_1739685048877.mp3 --video_out_path /home/kostafun/Projects/vidcreate/data/results/result_1739685177200.mp4 --start_frame 0
python -m scripts.inference --unet_config_path configs/unet/second_stage.yaml --inference_ckpt_path checkpoints/latentsync_unet.pt --guidance_scale 1 --video_path /home/kostafun/Projects/vidcreate/data/videos/nakortah_00001.mp4 --audio_path /home/kostafun/Projects/vidcreate/data/voices/voice_1739685343927.mp3 --video_out_path /home/kostafun/Projects/vidcreate/data/results/result_1739685402309.mp4 --start_frame 0
python -m scripts.inference --unet_config_path configs/unet/second_stage.yaml --inference_ckpt_path checkpoints/latentsync_unet.pt --guidance_scale 1 --video_path /home/kostafun/Projects/vidcreate/data/videos/nakortah_00001.mp4 --audio_path /home/kostafun/Projects/vidcreate/data/voices/voice_1739685436276.mp3 --video_out_path /home/kostafun/Projects/vidcreate/data/results/result_1739685454863.mp4 --start_frame 0
python -m scripts.inference --unet_config_path configs/unet/second_stage.yaml --inference_ckpt_path checkpoints/latentsync_unet.pt --guidance_scale 1 --video_path /home/kostafun/Projects/vidcreate/data/videos/angel2_faceswap.mp4 --audio_path /home/kostafun/Projects/vidcreate/data/voices/voice_1739685485248.mp3 --video_out_path /home/kostafun/Projects/vidcreate/data/results/result_1739685503270.mp4 --start_frame 0
